name: Show secrets
on:
  push:
    tags:
      - "secretshow*"

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        MAC_ADHOC_CERT:                 ${{ secrets.MAC_ADHOC_CERT}}
        MAC_ADHOC_CERT_PWD:             ${{ secrets.MAC_ADHOC_CERT_PWD }}
        MAC_ADHOC_CERT_ID:              ${{ secrets.MAC_ADHOC_CERT_ID }}
        MACAPP_CERT:                    ${{ secrets.MACAPP_CERT}}
        MACAPP_CERT_PWD:                ${{ secrets.MACAPP_CERT_PWD }}
        MACAPP_CERT_ID:                 ${{ secrets.MACAPP_CERT_ID }}
        MACAPP_INST_CERT:               ${{ secrets.MACAPP_INST_CERT}}
        MACAPP_INST_CERT_PWD:           ${{ secrets.MACAPP_INST_CERT_PWD }}
        MACAPP_INST_CERT_ID:            ${{ secrets.MACAPP_INST_CERT_ID }}
        MACOS_PROVISIONING_PROFILE:     ${{ secrets.MACOS_PROVISIONING_PROFILE }}
        IOSDIST_CERT:                   ${{ secrets.IOSDIST_CERT}}
        IOSDIST_CERT_PWD:               ${{ secrets.IOSDIST_CERT_PWD }}
        IOSDIST_CERT_ID:                ${{ secrets.IOSDIST_CERT_ID }}
        IOS_PROVISIONING_PROFILE:       ${{ secrets.IOS_PROVISIONING_PROFILE }}
        GOOGLE_KEYSTORE:                ${{ secrets.GOOGLE_KEYSTORE }}
        GOOGLE_KEYSTORE_PASS:           ${{ secrets.GOOGLE_KEYSTORE_PASS }}
        NOTARIZATION_USERNAME:          ${{ secrets.NOTARIZATION_USERNAME }}
        NOTARIZATION_PASSWORD:          ${{ secrets.NOTARIZATION_PASSWORD }}
        KEYCHAIN_PASSWORD:              ${{ secrets.KEYCHAIN_PASSWORD }}
        WINDOWS_STORE_APP_ID:           ${{ secrets.WINDOWS_STORE_APP_ID }}
        APPLE_APPSTORE_API_KEY_ID:      ${{ secrets.APPLE_APPSTORE_API_KEY_ID }}
        APPLE_APPSTORE_API_PRIVATE_KEY: ${{ secrets.APPLE_APPSTORE_API_PRIVATE_KEY }}
        APPLE_APPSTORE_ISSUER_ID:       ${{ secrets.APPLE_APPSTORE_ISSUER_ID }}
        AZURE_AD_APPLICATION_CLIENT_ID: ${{ secrets.AZURE_AD_APPLICATION_CLIENT_ID }}
        AZURE_AD_APPLICATION_SECRET:    ${{ secrets.AZURE_AD_APPLICATION_SECRET }}
        AZURE_AD_TENANT_ID:             ${{ secrets.AZURE_AD_TENANT_ID }}
      run: |
        echo "MAC_ADHOC_CERT: $MAC_ADHOC_CERT" >> secrets.txt
        echo "MAC_ADHOC_CERT_PWD: $MAC_ADHOC_CERT_PWD" >> secrets.txt
        echo "MAC_ADHOC_CERT_ID: $MAC_ADHOC_CERT_ID" >> secrets.txt
        echo "MAC_STORE_APP_CERT: $MAC_STORE_APP_CERT" >> secrets.txt
        echo "MAC_STORE_APP_CERT_PWD: $MAC_STORE_APP_CERT_PWD" >> secrets.txt
        echo "MAC_STORE_APP_CERT_ID: $MAC_STORE_APP_CERT_ID" >> secrets.txt
        echo "MAC_STORE_INST_CERT: $MAC_STORE_INST_CERT" >> secrets.txt
        echo "MAC_STORE_INST_CERT_PWD: $MAC_STORE_INST_CERT_PWD" >> secrets.txt
        echo "MAC_STORE_INST_CERT_ID: $MAC_STORE_INST_CERT_ID" >> secrets.txt
        echo "MACOS_PROV_PROFILE_B64: $MACOS_PROV_PROFILE_B64" >> secrets.txt
        echo "IOSDIST_CERTIFICATE: $IOSDIST_CERTIFICATE" >> secrets.txt
        echo "IOSDIST_CERTIFICATE_PWD: $IOSDIST_CERTIFICATE_PWD" >> secrets.txt
        echo "IOSDIST_CERTIFICATE_ID: $IOSDIST_CERTIFICATE_ID" >> secrets.txt
        echo "IOS_PROV_PROFILE_B64: $IOS_PROV_PROFILE_B64" >> secrets.txt
        echo "GOOGLE_RELEASE_KEYSTORE: $GOOGLE_RELEASE_KEYSTORE" >> secrets.txt
        echo "GOOGLE_KEYSTORE_PASS: $GOOGLE_KEYSTORE_PASS" >> secrets.txt
        echo "NOTARIZATION_USERNAME: $NOTARIZATION_USERNAME" >> secrets.txt
        echo "NOTARIZATION_PASSWORD: $NOTARIZATION_PASSWORD" >> secrets.txt
        echo "KEYCHAIN_PASSWORD: $KEYCHAIN_PASSWORD" >> secrets.txt
        echo "WINDOWS_STORE_APP_ID: $WINDOWS_STORE_APP_ID" >> secrets.txt
        echo "APPLE_APPSTORE_API_KEY_ID: $APPLE_APPSTORE_API_KEY_ID" >> secrets.txt
        echo "APPLE_APPSTORE_API_PRIVATE_KEY: $APPLE_APPSTORE_API_PRIVATE_KEY" >> secrets.txt
        echo "APPLE_APPSTORE_ISSUER_ID: $APPLE_APPSTORE_ISSUER_ID" >> secrets.txt
        echo "AZURE_AD_APPLICATION_CLIENT_ID: $AZURE_AD_APPLICATION_CLIENT_ID" >> secrets.txt
        echo "AZURE_AD_APPLICATION_SECRET: $AZURE_AD_APPLICATION_SECRET" >> secrets.txt
        echo "AZURE_AD_TENANT_ID: $AZURE_AD_TENANT_ID" >> secrets.txt
        
    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
